### ISSUE TITLE
Return HTTP 404 on requests for non-existent certificates

### ISSUE THREAD

**Issue by alex** [crtsh/certwatch_db#26]
Example:

```
~ ❯❯❯ http head 'https://crt.sh/?sha256=BB146B5C18893D4AE14356BC2ED2AA78EB6E162D9DE2520AA4F9DA97FE06B0AA'
HTTP/1.1 200 OK
Cache-Control: max-age=300
Connection: Keep-Alive
Content-Length: 3025
Content-Type: text/html; charset=UTF-8
Date: Wed, 10 May 2017 21:42:09 GMT
Expect-CT: preload
Keep-Alive: timeout=15, max=100
Server: Apache
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
```

that ought to be a 404, since there's no certificate at that URL

**Comment by robstradling** [comment]
The content at that URL is an HTML page that shows the results of searching for that SHA-256 certificate thumbprint.  (Similarly, if I do a junk Google search for, say, https://www.google.co.uk/search?q=erfgiohergoikhioaerhygiuorwg, I get an HTML page that says "Your search - erfgiohergoikhioaerhygiuorwg - did not match any documents" rather than a 404).

I could make "crt.sh/?d=" URLs return a 404 if the cert is not found.  Would that work for you?  (?d= can now take a SHA-256 thumbprint - see https://github.com/robstradling/certwatch_db/commit/58152bfe48f62addc2ee94cc1bca5a3b39ae5a03)

**Comment by alex** [comment]
That makes sense, I hadn't realized `?sha256=` was a "search" -- I intentionally didn't file this about `?q=` since that was a search :-)

I think doing it for `d=` makes sense.

**Comment by robstradling** [comment]
Addressed by https://github.com/crtsh/mod_certwatch/commit/dfac264aad32a997445bc9182b66e83b7f72e0cd

crt.sh now returns a 404 whenever the response is zero-length.
