### ISSUE TITLE
Replace integer by bigint

### ISSUE THREAD

**Issue by BenBE** [crtsh/certwatch_db#27]
Due to range of accepted values it might be worth replacing

* integer -> bigint
* serial -> bigserial

for record ID and foreigh indices as documented in the [PostgreSQL manual](https://www.postgresql.org/docs/current/static/datatype-numeric.html).

Given we currently handle about 100-200 million certificates, this might soon reach the constraints imposed by the smaller int32-based data types.

**Comment by robstradling** [comment]
Thanks for filing this.  I think it'll probably be a few years before we overflow 32bits, but you're right that this needs doing.

**Comment by robstradling** [comment]
`SELECT 2147483647 - max(id) FROM certificate;` returned 207011398 just now.

**Comment by robstradling** [comment]
`SELECT 2147483647 - max(id) FROM certificate;` returned 206768255 just now.  Assuming the rate of growth over the past ~1hr continues indefinitely, we'll hit 32-bit signed integer overflow in ~1 month.  The −2,147,483,648..0 range would only keep us going for ~1 year beyond that.
The rate of growth I've just measured is a bit inflated, because crt.sh is still catching up on a backlog; however, it seems likely that the actual rate of growth will continue to increase.

**Comment by robstradling** [comment]
`SELECT 2147483647 - max(id) FROM certificate;` returned 118265241 just now.

**Comment by stayallive** [comment]
I've already hit it on my instance, so yeah, `bigint` is a good call 😉

**Comment by robstradling** [comment]
crt.sh ran out of numbers at 05:55 UTC yesterday.  :-(

https://crt.sh/forum?place=msg%2Fcrtsh%2FDM8SI-qsE8E%2FJ_ndSkroBgAJ

**Comment by robstradling** [comment]
The new crt.sh service just went live (see https://crt.sh/forum?place=msg%2Fcrtsh%2FDM8SI-qsE8E%2Fd9AtKFD5BgAJ).

It won't run out of numbers any time soon! :-D
