### ISSUE TITLE
Manually trigger re-check of OCSP responder querying

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#49]
**As** operator of the OCSP monitoring service at Siemens CA

**I would like to have** the possibility to manually trigger the check of my OCSP responder to unknown serial numbers on https://crt.sh/ocsp-response?caID=52410&url=http%3A%2F%2Focsp1.pki-services.siemens.com&request=randomserial

**to** reproduce crt.sh queries to ensure that I filter them out correctly

![image](https://user-images.githubusercontent.com/1633499/42932313-3d092884-8b42-11e8-9efb-5bf2db21f873.png)

**Comment by robstradling** [comment]
If you psql to crt.sh:5432, you can trigger an unknown serial OCSP check by doing this:
`select ocsp_randomserial_embedded(certificate, 'http://ocsp1.pki-services.siemens.com')
    from certificate
    where id=174851777;`

(Note: This won't update the details on https://crt.sh/ocsp-responders, since you're only accessing a read-only slave crt.sh DB.  That page is updated by an instance of https://github.com/crtsh/ocsp_monitor that we run internally).
