### ISSUE TITLE
Queries with a limit of 999 results

### ISSUE THREAD

**Issue by franccesco** [crtsh/certwatch_db#70]
I've noticed that some queries have a limit of 999 results when appending `&output=json`, which is fine actually, but is there a way to get the rest of the results? Maybe a pagination option on the URL?

![image](https://user-images.githubusercontent.com/6962824/69500951-9a66dc80-0ec5-11ea-97e1-3c6f5346207a.png)

Example: `https://crt.sh/?dNSName=%25edu.ni&output=json`

**Comment by robstradling** [comment]
This was due to https://crt.sh/forum?place=msg%2Fcrtsh%2FPJBu5cvm0G8%2FiCIy0vBPAwAJ.  I'm not sure how I managed to implement a limit of 1000 but write "10000" in that post.  Sorry about that!

The new crt.sh system (launched yesterday) definitely does have a 10000 limit.  https://crt.sh/?dNSName=edu.ni&output=json currently returns 3271 entries.

(Unfortunately, removing this 10000 limit causes crt.sh to fall over, due to the volume of searches that users keep performing for domain names for which there are hundreds of thousands of certs).
