### ISSUE TITLE
Include Root CA which are not part of a root program

### ISSUE THREAD

**Issue by RufusJWB** [crtsh/certwatch_db#75]
Is it possible to add/upload Root CA, which are not part of a root program to crt.sh db? Currently all of them are mapped to https://crt.sh/?caid=-1 and it would be great, if we could upload the correct CA certificates.

**Comment by robstradling** [comment]
@RufusJWB Yes, I can manually import root certificates into the crt.sh database.  Feel free to provide them here or send me an email.

**Comment by RufusJWB** [comment]
@robstradling for my use case:

- http://www.siemens.com/pki/ZZZZZZA1.crt 
- http://www.siemens.com/pki/ZZZZZZV1.crt
- http://www.siemens.com/pki/ZZZZZ000.crt

would be sufficient.

**Comment by robstradling** [comment]
Those 3 root certs are actually in the crt.sh database already:
https://crt.sh/?id=2961100804
https://crt.sh/?id=2961100809
https://crt.sh/?id=2961100803

I suspect they were found and automatically added when https://github.com/crtsh/caissuer_monitor first ran.  This could explain the `certificate.ISSUER_CA_ID` problem: the CA records for these roots didn't exist when issued certs with lower IDs were added to the database.

I just ran a script to fixup as many instances of `certificate.ISSUER_CA_ID=-1` as possible.  `select count(*) from certificate where issuer_ca_id=-1;` now reports 267 instead of 421.

**Comment by RufusJWB** [comment]
Top! Thank you very much!
